import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, expect, it, vi } from "vitest";
import { TaskProvisioningService, TaskProvisioningStore } from "../src/task-provisioning.js";
const dirs: string[] = [];
function setup() { const dir = mkdtempSync(path.join(tmpdir(), "provision-")); dirs.push(dir); const file = path.join(dir, "state.sqlite"); const store = new TaskProvisioningStore(file); return { file, store, service: new TaskProvisioningService(store) }; }
afterEach(() => { for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true }); });
const input = { operationId: "inbox:-1001:8:123", sourceContextKey: "-1001:8", sourceMessageIds: [123], title: "Investigate", workspace: "/work", kind: "inbox" as const };
function transport() { return { createTopic: vi.fn(async () => 22), bind: vi.fn(async () => {}), ready: vi.fn(async () => {}) }; }
it("persists acceptance before creation and deduplicates across restart", async () => { const { file, store, service } = setup(); const t = transport(); t.createTopic.mockImplementation(async () => { expect(store.get(input.operationId)?.state).toBe("provisioning"); return 22; }); expect((await service.provision(input, t)).state).toBe("ready"); store.close(); const restarted = new TaskProvisioningStore(file); expect((await new TaskProvisioningService(restarted).provision(input, t)).messageThreadId).toBe(22); expect(t.createTopic).toHaveBeenCalledTimes(1); restarted.close(); });
it("does not recreate an ambiguous timed out creation", async () => { const { service, store } = setup(); const t = transport(); t.createTopic.mockRejectedValue(new Error("timeout")); expect((await service.provision(input, t)).state).toBe("unknown"); await service.provision(input, t); expect(t.createTopic).toHaveBeenCalledTimes(1); store.close(); });
it("records explicit 429 as failed", async () => { const { service, store } = setup(); const t = transport(); t.createTopic.mockRejectedValue({ error_code: 429 }); expect((await service.provision(input, t)).state).toBe("failed"); store.close(); });
it("recovers a confirmed topic after restart before binding", async () => { const { file, store } = setup(); store.accept(input); store.patch(input.operationId, { state: "provisioning", messageThreadId: 22 }); store.close(); const restarted = new TaskProvisioningStore(file); const t = transport(); expect((await new TaskProvisioningService(restarted).provision(input, t)).state).toBe("ready"); expect(t.createTopic).not.toHaveBeenCalled(); expect(t.bind).toHaveBeenCalledTimes(1); restarted.close(); });
it("marks interrupted creation without a topic ID unknown", async () => { const { store, service } = setup(); store.accept(input); store.patch(input.operationId, { state: "provisioning" }); const t = transport(); expect((await service.provision(input, t)).state).toBe("unknown"); expect(t.createTopic).not.toHaveBeenCalled(); store.close(); });
it("retains the topic and readiness failure separately", async () => { const { store, service } = setup(); const t = transport(); t.ready.mockRejectedValue(new Error("attachment failed")); expect(await service.provision(input, t)).toMatchObject({ state: "failed", messageThreadId: 22, failureStage: "ready" }); store.close(); });
it("rejects reuse of an operation ID for a different source", async () => { const { store, service } = setup(); const t = transport(); await service.provision(input, t); await expect(service.provision({ ...input, sourceContextKey: "-1002:8" }, t)).rejects.toThrow("identity"); store.close(); });
it("drains running creation before disposal and rejects fresh work", async () => { const { service } = setup(); let release!: () => void; const gate = new Promise<void>(resolve => { release = resolve; }); const t = transport(); t.createTopic.mockImplementation(async () => { await gate; return 22; }); const run = service.provision(input, t); let closed = false; const dispose = service.dispose().then(() => { closed = true; }); await Promise.resolve(); expect(closed).toBe(false); await expect(service.provision({ ...input, operationId: "second" }, t)).rejects.toThrow("stopping"); release(); expect((await run).state).toBe("ready"); await dispose; expect(closed).toBe(true); });
